services:
  blog:
    build:
      context: .
      dockerfile: Dockerfile.build
    container_name: my-blog
    ports:
      - "8092:80"
    restart: unless-stopped
    labels:
      - "description=Gatsby Blog"
      - "version=1.0.0"
